# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/bytedance/Fastbot_iOS'
target 'iOS_interView' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
pod'Aspects'
pod'Masonry'
pod'SDWebImage', '~>5.0'
#pod'YYImage'
#pod'YYWebImage'
pod'AFNetworking'
pod'FMDB'
pod'MJExtension'
pod'ZLPhotoBrowser'
pod'PLCrashReporter'
pod'KSCrash'
pod'YYKit'
#pod 'CL_ShanYanSDK', '<=2.3.4.5'
pod 'AvoidCrash'
#pod 'Fastbot'
  # Pods for iOS_interView

end
