# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_interView_Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#pod'SwiftyJSON'

  # Pods for iOS_interView_Swift

end
